name: Set up JIMM
description: Set up JIMM with provided configuration.
inputs:
  jimm-version:
    description: Version of JIMM to use.
    required: false
    default: dev
  juju-channel:
    description: Channel of Juju to use.
    required: false
    default: 3/stable
  dashboard-location:
    description: URL of the running dashboard.
    required: false
    default: http://127.0.0.1:8000
  ghcr-secret:
    description: GHCR secret.
    required: true
outputs:
  controller-name:
    description: Name of the Juju controller
    value: ${{ steps.test-server.outputs.controller-name }}

runs:
  using: composite
  steps:
    - name: Checkout JIMM repo
      uses: actions/checkout@v4
      with:
        repository: canonical/jimm
        path: ./jimm
    - name: Update dashboard location for JIMM
      shell: bash
      run:
        yq -i '
          .services.jimm-base.environment.JIMM_DASHBOARD_FINAL_REDIRECT_URL = "${{ inputs.dashboard-location }}" |
          .services.jimm-base.environment.CORS_ALLOWED_ORIGINS = "${{ inputs.dashboard-location }}" |
          .services.jimm-base.environment.JIMM_DASHBOARD_LOCATION = "${{ inputs.dashboard-location }}"'
          "jimm/docker-compose.common.yaml"
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'jimm/go.mod'
    - name: Go vendor to speed up docker build
      shell: bash
      run: cd jimm && go mod vendor
    - name: Start JIMM (pull request)
      uses: ./jimm/.github/actions/test-server
      id: test-server
      with:
        jimm-version: ${{ inputs.jimm-version }}
        juju-channel: ${{ inputs.juju-channel }}
        ghcr-pat: ${{ inputs.ghcr-secret }}
    - name: Restart JIMM # NOTE: This is required due to a JIMM bug.
      shell: bash
      run: docker restart jimm
